// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace SmartTaxi.iOS
{
	public partial class AuthView3Controller : UIViewController
	{
		public AuthView3Controller (IntPtr handle) : base (handle)
		{
		}
	}
}
