// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using System.Collections.Generic;

namespace SmartTaxi.iOS
{
	public partial class MainViewController : UIViewController
	{
		public MainViewController (IntPtr handle) : base (handle)
		{
		}

		public override void AwakeFromNib ()
		{
			//this.Initialize ();
		}

		public void Initialize(){
			//var myStoryboard = AppDelegate.Storyboard;
			//var viewController = myStoryboard.InstantiateViewController ("SomeViewController") as UIViewController;
		}

		public override void ViewDidLoad ()
		{
			//this.scrollView.ScrollEnabled = true;
			//this.scrollView.Frame =  new System.Drawing.RectangleF(0,0,320,1000);
			//this.scrollView.ContentSize = new System.Drawing.SizeF (320, 1000);

			this.View.BackgroundColor = UIColor.FromRGB(255,216,0);
			this.tableview_Menu.BackgroundColor = UIColor.FromRGB(255,216,0);
			this.tableview_Menu.Source = new MenuDataSource (
				new List<MenuItem> { 
					new MenuItem{ Name = "Откуда", ImageName = "from.png", Color=UIColor.FromRGB(255,216,0)},
					new MenuItem{ Name = "Куда", ImageName = "to.png", Color=UIColor.FromRGB(255,204,0)},
					new MenuItem{ Name = "Когда", ImageName = "when.png", Color=UIColor.FromRGB(255,185,1)}, 
					new MenuItem{ Name = "Примечание", ImageName = "pen.png", Color=UIColor.FromRGB(255,168,0)}, 
					new MenuItem{ Name = "Вызвать", ImageName = "car.png", Color=UIColor.FromRGB(255,144,0)}, 
					new MenuItem{ Name = "Я - водитель", ImageName = "id.png", Color=UIColor.FromRGB(255,133,0)}
				});
			this.tableview_Menu.Frame = new System.Drawing.RectangleF (0, 0, this.View.Frame.Width, this.tableview_Menu.Frame.Height + this.NavigationController.NavigationBar.Frame.Height);
		}

		public override void ViewWillAppear (bool animated)
		{
			this.NavigationController.NavigationBar.Hidden = true;
			base.ViewWillAppear (animated);
		}
	}
}
