// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using Google.Maps;
using System.Drawing;

namespace SmartTaxi.iOS
{
	public partial class WhenViewController : UIViewController
	{
		public WhenViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			AppDelegate.AddGestureRecognizer (this.View);

			_previewImg.Image = UIImage.FromBundle ("Menu/when.png");
			_okBtn.SetImage (UIImage.FromBundle ("Common/ok.png"), UIControlState.Normal);

			_headerLabel.Font = UIFont.FromName (AppDelegate.FontRobotoCondensedLight,25f);

			_explanationTextView.Font = UIFont.FromName (AppDelegate.FontRobotoCondensedLight,15f);

			_periodPickerView.Model = new PeriodPickerView (this);




			_okBtn.TouchUpInside += (sender, e) => {
				int hour = int.Parse((_periodPickerView.Model as PeriodPickerView).hourSelected);
				int minute = int.Parse((_periodPickerView.Model as PeriodPickerView).minuteSelected);
				AppDelegate.Order.Minutes = hour*60 + minute;
				var vController = (AppDelegate.Storyboard.InstantiateViewController ("CommentViewController") as UIViewController);
				this.NavigationController.PushViewController (vController, true);
			};
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			if (AppDelegate.Order.Minutes == 0) {
				_periodPickerView.Select (1, 0, false);
				_periodPickerView.Select (30, 2, false);
			} else {
				int hour = AppDelegate.Order.Minutes / 60;
				int minute = AppDelegate.Order.Minutes % 60;

				_periodPickerView.Select (hour, 0, false);
				_periodPickerView.Select (minute, 2, false);
			}

		}
	}
}
