// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using Google.Maps;
using System.Drawing;

namespace SmartTaxi.iOS
{
	public partial class WhenViewController : UIViewController
	{
		public WhenViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			AppDelegate.AddGestureRecognizer (this.View);

			_previewImg.Image = UIImage.FromBundle ("Menu/when.png");
			_okBtn.SetImage (UIImage.FromBundle ("Common/ok.png"), UIControlState.Normal);

			_headerLabel.Font = UIFont.FromName (AppDelegate.FontRobotoCondensedLight,25f);

			_explanationTextView.Font = UIFont.FromName (AppDelegate.FontRobotoCondensedLight,15f);

			_periodPickerView.Model = new PeriodPickerView (this);
			_periodPickerView.Select (1, 0, false);
			_periodPickerView.Select (29, 2, false);

		}
	}
}
