// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using System.Drawing;

namespace SmartTaxi.iOS
{
	public partial class InstructionsViewController : UIViewController
	{
		private UIImageView[] pages;

		public InstructionsViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewWillAppear (bool animated)
		{
			this.NavigationController.NavigationBar.Hidden = true;
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			_img1.Image = UIImage.FromBundle ("Instructions/icon-info.png");
			_btn2.SetImage(UIImage.FromBundle ("Instructions/icon-cancel.png"), UIControlState.Normal);
			_text1.Text = "Следите за статусами заказов.";
			_text1.Font = UIFont.FromName (AppDelegate.FontRobotoCondensedLight,20f);

			_btn2.TouchUpInside += (sender, e) => {
				this.NavigationController.PopViewControllerAnimated(true);
			};

			this.scroll.DecelerationEnded += this.scroll_DecelerationEnded;
			this.pager.ValueChanged += this.pager_ValueChanged;

			this.scroll.ShowsVerticalScrollIndicator = false;
			this.scroll.ShowsHorizontalScrollIndicator = false;

			RectangleF pageFrame = this.scroll.Frame;
			this.scroll.Frame = new RectangleF (0, 0, this.View.Frame.Width, pageFrame.Height-94);
			this.scroll.ContentSize = new SizeF (pageFrame.Width * 4, this.View.Frame.Height);
			this.scroll.ContentOffset = new PointF (0, 0);
			this.scroll.PagingEnabled = true;

			this.pages = new UIImageView[4];

			this.pages [0] = new UIImageView (pageFrame);
			this.pages [0].ContentMode = UIViewContentMode.ScaleToFill;
			this.pages [0].Image = UIImage.FromBundle("Instructions/instruction1.png");

			pageFrame.X += this.scroll.Frame.Width;

			this.pages [1] = new UIImageView (pageFrame);
			this.pages [1].ContentMode = UIViewContentMode.ScaleToFill;
			this.pages [1].Image = UIImage.FromBundle("Instructions/instruction2.png");

			pageFrame.X += this.scroll.Frame.Width;

			this.pages [2] = new UIImageView (pageFrame);
			this.pages [2].ContentMode = UIViewContentMode.ScaleToFill;
			this.pages [2].Image = UIImage.FromBundle("Instructions/instruction3.png");

			pageFrame.X += this.scroll.Frame.Width;

			this.pages [3] = new UIImageView (pageFrame);
			this.pages [3].ContentMode = UIViewContentMode.ScaleToFill;
			this.pages [3].Image = UIImage.FromBundle("Instructions/instruction4.png");

			foreach (var page in this.pages) {
				this.scroll.AddSubview (page);
			}
		}


		private void scroll_DecelerationEnded (object sender, EventArgs e)
		{
			float x1 = this.pages[0].Frame.X;
			float x2 = this.pages[1].Frame.X;
			float x3 = this.pages[2].Frame.X;

			float x = this.scroll.ContentOffset.X;

			if (x == x1)
			{
				this.pager.CurrentPage = 0;
				_text1.Text = "Следите за статусами заказов.";
			} 
			else if (x == x2)
			{
				this.pager.CurrentPage = 1;
				_text1.Text = "Задайте стоимость поездки.";
			} 
			else if (x== x3)
			{
				this.pager.CurrentPage = 2;
				_text1.Text = "Отслеживайте клиента в реальном времени.";
			} 
			else
			{
				this.pager.CurrentPage = 3;
				_text1.Text = "Пополняйте баланс в платежных терминалах.";
			}
		}

		private void pager_ValueChanged (object sender, EventArgs e)
		{
			PointF contentOffset =
				this.scroll.ContentOffset;
			switch (this.pager.CurrentPage)
			{
			case 0:
				contentOffset.X = this.pages[0].Frame.X;
				this.scroll.SetContentOffset (contentOffset, true);
				break;
			case 1:
				contentOffset.X = this.pages[1].Frame.X;
				this.scroll.SetContentOffset (contentOffset, true);
				break;
			case 2:
				contentOffset.X = this.pages[2].Frame.X;
				this.scroll.SetContentOffset (contentOffset, true);
				break;
			case 3:
				contentOffset.X = this.pages[3].Frame.X;
				this.scroll.SetContentOffset (contentOffset, true);
				break;
			default:
				// do nothing
				break;
			}
		}
	}
}
