// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace SmartTaxi.iOS
{
	public partial class ProfileViewController : UIViewController
	{
		public ProfileViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			AppDelegate.AddGestureRecognizer (this.View);

			//_scrollView.ScrollEnabled = true;
			//_scrollView.Frame = new System.Drawing.RectangleF (0, 0, this.View.Frame.Width, this.View.Frame.Height);
			//_scrollView.ContentSize = new System.Drawing.SizeF (0, 745);

			_previewImg.Image = UIImage.FromBundle ("Menu/id.png");
			_headerLabel.Font = UIFont.FromName (AppDelegate.FontRobotoCondensedLight,25f);
			_backButton.SetImage (UIImage.FromBundle ("Common/back.png"), UIControlState.Normal);



			_fioLabel.Font = UIFont.FromName (AppDelegate.FontRobotoCondensedLight,20f);
			_ratedLabel.Font = UIFont.FromName (AppDelegate.FontRobotoCondensedLight,18f);

			_starImageView.Image = UIImage.FromBundle ("Common/star.png");
			_star2ImageView.Image = UIImage.FromBundle ("Common/star.png");
			_star3ImageView.Image = UIImage.FromBundle ("Common/star.png");
			_star4ImageView.Image = UIImage.FromBundle ("Common/star.png");
			_star5ImageView.Image = UIImage.FromBundle ("Common/star.png");


			_modelHeaderLabel.Font = UIFont.FromName (AppDelegate.FontRobotoCondensedLight,18f);
			_modelValueLabel.Font = UIFont.FromName (AppDelegate.FontRobotoCondensedLight,20f);
			_markaHeader.Font = UIFont.FromName (AppDelegate.FontRobotoCondensedLight,18f);
			_markaValueLabel.Font = UIFont.FromName (AppDelegate.FontRobotoCondensedLight,20f);
			_numberHeaderLabel.Font = UIFont.FromName (AppDelegate.FontRobotoCondensedLight,18f);
			_numberValueLabel.Font = UIFont.FromName (AppDelegate.FontRobotoCondensedLight,20f);
			_colorHeaderLabel.Font = UIFont.FromName (AppDelegate.FontRobotoCondensedLight,18f);
			_colorValueLabel.Font = UIFont.FromName (AppDelegate.FontRobotoCondensedLight,20f);

			_carImage.BackgroundColor = UIColor.Gray;


			_instructionButton.Layer.BackgroundColor = UIColor.Clear.CGColor;
			_instructionButton.Layer.BorderWidth = 2;
			_instructionButton.Layer.BorderColor = AppDelegate.AppColorYellow.CGColor;
			_instructionButton.Font = UIFont.FromName (AppDelegate.FontRobotoCondensedLight,18f);
			_instructionButton.TouchUpInside += (sender, e) => {
				var vController = (AppDelegate.Storyboard.InstantiateViewController ("InstructionsViewController") as UIViewController); 
				NavigationController.PushViewController (vController, false);
			};

			_identificatorLabel.Font = UIFont.FromName (AppDelegate.FontRobotoCondensedLight,18f);

			_identificatorTextField.Layer.BackgroundColor = AppDelegate.AppColorHalfYellow.CGColor;
			_identificatorTextField.Layer.BorderWidth = 2;
			_identificatorTextField.Layer.BorderColor = AppDelegate.AppColorYellow.CGColor;
			_identificatorTextField.Font = UIFont.FromName (AppDelegate.FontRobotoCondensedLight,18f);




			_okBtn.SetImage (UIImage.FromBundle ("Common/ok.png"), UIControlState.Normal);
		}
	}
}
